### ISSUE TITLE
Sound recording setting doesn't work

### ISSUE THREAD

**Issue by katoquro** [phw/peek#1061]
**System Information**

* Distribution package: apt
* Peek version: 1.5.1
* GTK: 4.6.2  3.24.33  2.24.33
* Additional info if applicable: ubuntu 22.04

**Describe the bug**
peek records sound all the time when video (like mp4) is recorded despite the setting checkbox state 

**To Reproduce**
1. Play music through the laptop speakers 
2. Start peek
3. Disable sound recording in settings
4. Record the screen for 5 seconds in MP4
5. Play recorder video (it  will contains sound)

**Expected behavior**
no sound was recorder

**Comment by genygilles** [comment]
Version 1.5.1 has been released in February 2020, meanwhile I think it might have been fixed: https://github.com/phw/peek/commit/1044f270246aa2014350cc701fd47477d523b515

**Comment by katoquro** [comment]
Yes. I've installed `Peek 1.5.1` from ubuntu repo :shrug:. 
Now I have version from PPA  (it's also 1.5.1 but from the end of 2021- `peek/jammy,now 1.5.1+git20211214-1 amd64 [installed]`) and the issue is still there. Now it records sound only for several seconds and at very low volume) but records

**Comment by dimuska139** [comment]
How to disable sound recording? Maybe do you know it?

**Comment by dimuska139** [comment]
This is a very annoying problem. To remove sound from a video, you have to separately use the following command: _ffmpeg -i $input_file -c copy -an $output_file_. This is very annoying when you need to record video frequently.

**Comment by sviricode** [comment]
@phw hello. When to expect a package update in the official Ubuntu repository?

**Comment by dimuska139** [comment]
@phw hello. When to expect a package update in the official Ubuntu repository?
